function generateWordplayFragment() {
  // prettier-ignore
  const wordplays = [
    'a-peeling-personality',
    'a-salt-and-battery',
    'a-thyme-to-kill',
    'aisle-be-there',
    'amped-up',
    'artichoked-up',
    'bark-up-the-right-tree',
    'barking-up-the-write-tree',
    'batter-days-ahead',
    'batter-late-than-never',
    'bee-my-honey',
    'bee-spoke-tailoring',
    'beet-around-the-bush',
    'bloom-and-gloom',
    'bread-and-butterflies',
    'breadwinner-takes-all',
    'brewed-awakening',
    'bridal-shower-power',
    'bunny-business',
    'canine-to-five',
    'carrot-on',
    'cereal-killer',
    'chalk-it-up',
    'cheese-the-day',
    'chill-pill',
    'clause-and-effect',
    'clocking-out',
    'clone-alone',
    'cone-of-silence',
    'couch-potato-peeling',
    'couch-surfing-safari',
    'deer-diary',
    'dough-or-die',
    'duck-and-cover',
    'easel-does-it',
    'egg-straordinary',
    'feather-forecast',
    'fleet-of-foot',
    'flight-of-fancy',
    'fowl-mood',
    'fowl-play',
    'frolic-and-detour',
    'fur-the-record',
    'ghost-write',
    'glove-story',
    'gnome-sweet-gnome',
    'grain-of-truth',
    'hair-to-the-throne',
    'hare-raising-tale',
    'hedge-your-bets',
    'ink-redible-journey',
    'knead-to-know-basis',
    'knight-school',
    'knight-shift',
    'knighty-night',
    'knot-my-problem',
    'leap-of-faith',
    'leap-of-page',
    'lettuce-celebrate',
    'lime-and-punishment',
    'mewsic-to-my-ears',
    'mime-your-business',
    'mint-condition',
    'mint-to-be',
    'mist-opportunity',
    'mute-point',
    'owl-be-back',
    'pane-and-gain',
    'pasta-point',
    'paw-sitive-vibes',
    'paws-and-reflect',
    'paws-for-effect',
    'pear-pressure',
    'petal-to-the-metal',
    'pigment-of-imagination',
    'pitcher-perfect',
    'plenty-of-fish-in-the-sea',
    'purr-plexed',
    'purrfect-crime',
    'quack-medicine',
    'raining-cats-and-frogs',
    'rock-and-roll-call',
    'seamless-transition',
    'sew-far-sew-good',
    'sew-it-goes',
    'slice-of-life',
    'sonnet-of-a-beach',
    'sparrow-time',
    'spool-of-thought',
    'sprout-of-the-blue',
    'stairway-to-haven',
    'stew-in-your-own-juice',
    'tale-of-two-kitties',
    "time-flies-when-you're-having-rum",
    'toad-ally-awesome',
    'whale-of-a-time',
    'wheely-tired',
    'wool-gathering',
    'wool-you-believe-it'
  ]

  return wordplays[Math.floor(Math.random() * wordplays.length)];
}

function generatePopCultureFragment() {
  // prettier-ignore
  const adjectives = [
    'able',         'absorbing',      'abundant',      'academic',
    'accomplished', 'accurate',       'active',        'adept',
    'adventurous',  'affectionate',   'agile',         'agreeable',
    'airy',         'alert',          'alluring',      'altruistic',
    'amazing',      'amazingly',      'amiable',       'amusing',
    'angelic',      'animated',       'antique',       'appetizing',
    'appreciative', 'approachable',   'aqua',          'aristocratic',
    'artful',       'artistic',       'artsy',         'astonishing',
    'astounding',   'athletic',       'awe-inspiring', 'awesome',
    'balanced',     'baroque',        'bashful',       'beaming',
    'beautiful',    'beloved',        'benevolent',    'bewitching',
    'bizarre',      'blazing',        'blissful',      'blithe',
    'bold',         'bouncing',       'breathtaking',  'breezy',
    'bright',       'bright-eyed',    'brilliant',     'candid',
    'captivating',  'charismatic',    'charming',      'cheeky',
    'cheerful',     'classy',         'clever',        'colorful',
    'comical',      'content',        'cool',          'cosmic',
    'coy',          'crafty',         'creative',      'crisp',
    'curious',      'cute',           'dancing',       'daring',
    'dazzling',     'delightful',     'dreamy',        'dynamic',
    'electric',     'enchanting',     'energetic',     'enthralling',
    'epic',         'exuberant',      'fabulous',      'fantastic',
    'festive',      'fierce',         'fiery',         'flamboyant',
    'frisky',       'frolicsome',     'gleaming',      'glorious',
    'graceful',     'grand',          'groovy',        'gutsy',
    'heartfelt',    'heroic',         'hilarious',     'honorable',
    'hypnotic',     'idealistic',     'impressive',    'incredible',
    'innovative',   'intrepid',       'jaunty',        'jazzy',
    'jolly',        'jovial',         'joyful',        'jubilant',
    'keen',         'kinetic',        'kingly',        'knockout',
    'kooky',        'laughing',       'legendary',     'lively',
    'luminous',     'lush',           'luxurious',     'magical',
    'majestic',     'marvelous',      'merry',         'mighty',
    'mystical',     'nifty',          'nimble',        'nostalgic',
    'notable',      'novel',          'optimal',       'opulent',
    'original',     'ornate',         'outstanding',   'peppy',
    'phenomenal',   'pioneering',     'playful',       'powerful',
    'quick',        'quintessential', 'quirky',        'quixotic',
    'radiant',      'radical',        'remarkable',    'resilient',
    'riveting',     'robust',         'sensational',   'shiny',
    'sneaky',       'sophisticated',  'sparkling',     'spectacular',
    'stellar',      'suave',          'sunny',         'tactful',
    'thrilling',    'trailblazing',   'tremendous',    'twinkling',
    'ultimate',     'unbelievable',   'unique',        'unrivaled',
    'unstoppable',  'valiant',        'vibrant',       'vigorous',
    'virtuoso',     'vivid',          'whimsical',     'whirlwind',
    'whiz-bang',    'winsome',        'witty',         'wondrous',
    'x-factor',     'xenial',         'xenodochial',   'xenophonic',
    'xtraordinary', 'yearning',       'yielding',      'youth-oriented',
    'youthful',     'yummy',          'zany',          'zealful',
    'zealous',      'zestful',        'zesty',         'zippy'
  ]

  // prettier-ignore
  const nouns =  [
    'acorn',       'anakin',         'anchor',     'apple',
    'ariel',       'arya',           'bb8',        'balloon',
    'banana',      'batman',         'blackwidow', 'bobafett',
    'bowser',      'bran',           'brienne',    'bronn',
    'broom',       'butterfly',      'c3po',       'cactus',
    'camel',       'captain-america','catelyn',    'cersei',
    'cherry',      'chewbacca',      'cupcake',    'cyclops',
    'daenerys',    'darthvader',     'davos',      'dolphin',
    'donkey-kong', 'donut',          'dragon',     'drogo',
    'duck',        'dumbledore',     'eagle',      'eggplant',
    'elephant',    'ellaria',        'elsa',       'envelope',
    'feather',     'finn',           'firefly',    'flamingo',
    'flash',       'frodo',          'frog',       'gandalf',
    'gazelle',     'gendry',         'ghost',      'giraffe',
    'glove',       'gollum',         'grapes',     'greyworm',
    'grievous',    'guitar',         'hansolo',    'harmonica',
    'harry-potter','hat',            'helmet',     'hermione',
    'hippo',       'hodor',          'homer',      'hulk',
    'ice-cream',   'icicle',         'iguana',     'ink',
    'ironman',     'jabba',          'jacket',     'jaime',
    'jangofett',   'jar',            'jellyfish',  'jewel',
    'joffrey',     'joker',          'jonsnow',    'kazoo',
    'kettle',      'kirby',          'kite',       'kitten',
    'koala',       'kyloren',        'lamp',       'lando',
    'leia',        'lemur',          'lighthouse', 'link',
    'lion',        'loki',           'luigi',      'luke-skywalker',
    'magnet',      'margaery',       'mario',      'maul',
    'melisandre',  'missandei',      'mongoose',   'monkey',
    'mountain',    'narwhal',        'necklace',   'ned',
    'nest',        'nut',            'nymeria',    'oberyn',
    'obiwan',      'oboe',           'octopus',    'orange',
    'owl',         'padme',          'palpatine',  'panda',
    'parrot',      'peach',          'penguin',    'pikachu',
    'pillow',      'podrick',        'quartz',     'quiche',
    'quill',       'quokka',         'r2d2',       'rabbit',
    'raccoon',     'ramsay',         'rey',        'rhaegal',
    'rickon',      'ring',           'robb',       'robot',
    'rogue',       'ronweasley',     'ros',        'rose',
    'samwell',     'sansa',          'shae',       'shaggydog',
    'sherlock',    'simba',          'snake',      'spiderman',
    'spock',       'squirrel',       'stannis',    'star',
    'storm',       'summer',         'sunflower',  'superman',
    'teapot',      'theon',          'thor',       'tiger',
    'tormund',     'train',          'turtle',     'tyrion',
    'ukulele',     'umbrella',       'unicorn',    'urchin',
    'van',         'vase',           'violin',     'viserion',
    'voldemort',   'vulture',        'walrus',     'whale',
    'wheel',       'windmill',       'wolverine',  'wonder-woman',
    'x-ray',       'xenops',         'xerus',      'xylophone',
    'yacht',       'yak',            'ygritte',    'yoda',
    'yogurt',      'yoyo',           'zebra',      'zelda',
    'zipper',      'zither',         'zucchini'
  ]

  return [
    adjectives[Math.floor(Math.random() * adjectives.length)],
    nouns[Math.floor(Math.random() * nouns.length)],
  ].join("-");
}

export function generateRandomFragment() {
  return [generatePopCultureFragment(), generateWordplayFragment()].join("-");
}
